const products = [
  {
    _id: '1',
    name: 'Boxing Gloves',
    image: '/images/boxinggloves.jpg',
    description: 'Boxing gloves for professionals and trainers',
    brand: 'Maxpot',
    category: 'MMA',
    price: 49.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Head Gears',
    image: '/images/headgear.jpg',
    description: 'Head Gears for safety while training',
    brand: 'Maxpot',
    category: 'MMA',
    price: 59.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Kick Pads',
    image: '/images/kickpads.jpg',
    description: 'Kick Pads for training purposes',
    brand: 'Maxpot',
    category: 'MMA',
    price: 45.55,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Punching Mitts',
    image: '/images/punchingmitts.jpg',
    description: 'Punching Mitts for trainers',
    brand: 'Maxpot',
    category: 'MMA',
    price: 39.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'MMA Gloves',
    image: '/images/mmagloves.jpg',
    description: 'MMA Gloves for professionals and trainers',
    brand: 'Everlast',
    category: 'MMA',
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Shinguards',
    image: '/images/shinguards.jpg',
    description: 'Shinguards for safety',
    brand: 'Everlast',
    category: 'MMA',
    price: 38.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
